project:
  type: website

website:
 
  cookie-consent:
    type: express
    style: headline
    palette: light
    
  title: "FUNAlytics Blog"
  favicon: "📊"
  site-url: https://funalytics.de 
  description: "This is Christian Jaehnert's personal Blog."
  navbar:

    right:
      - posts.qmd
      - icon: linkedin        
        href: https://www.linkedin.com/in/christian-jaehnert/
  
  page-footer:
    background: light
    left: Copyright 2025, Christian Jaehnert
    right: This website is built with ❤️ and [Quarto](https://quarto.org/)

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  
