project:
  type: website

website:
  title: "FUNAlytics Blog"
  site-url: https://funalytics.de 
  description: "This is Christian Jaehnert's personal Blog."
  navbar:

    right:
      - posts.qmd
      - about.qmd
      - icon: linkedin        
        href: https://www.linkedin.com/in/christian-jaehnert/
  
  page-footer:
    center: 
      - text: "(c) Christian Jaehnert"

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  
cookie-consent: true