<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Christian Jaehnert">
<meta name="dcterms.date" content="2025-05-20">

<title>Disentangling Effects: The Secret Behind Marketing Mix Models – FUNAlytics Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../📊" rel="icon">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">FUNAlytics Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/christian-jaehnert/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Disentangling Effects: The Secret Behind Marketing Mix Models</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Marketing Mix Modell</div>
                <div class="quarto-category">Disentangle Effects</div>
                <div class="quarto-category">Ice Cream</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Christian Jaehnert </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 20, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-magic-of-variance-in-marketing-mix-modeling" id="toc-the-magic-of-variance-in-marketing-mix-modeling" class="nav-link active" data-scroll-target="#the-magic-of-variance-in-marketing-mix-modeling">The Magic of Variance in Marketing Mix Modeling</a></li>
  <li><a href="#giving-intuition---ice-cream" id="toc-giving-intuition---ice-cream" class="nav-link" data-scroll-target="#giving-intuition---ice-cream">Giving Intuition - Ice Cream</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="the-magic-of-variance-in-marketing-mix-modeling" class="level3">
<h3 class="anchored" data-anchor-id="the-magic-of-variance-in-marketing-mix-modeling">The Magic of Variance in Marketing Mix Modeling</h3>
<p>Marketing Mix Modeling (MMM) is a statistical technique in econometrics that quantifies the impact of various marketing and sales activities on sales of a company. It also incorporates external factors that are typically beyond a company’s control, such as weather, holidays, or competitive activities.</p>
<p>Since I work in the area of MMM, I’m often asked a similar question:</p>
<p><strong>How can MMM actually disentangle the effects of various factors, like advertising campaigns across multiple media channels, POS promotions, or weather? How does this “disentangling” work?</strong></p>
<p>The answer lies in the concept of&nbsp;<strong>variance</strong>. By capturing and analyzing the variation in data, MMM can attribute changes in sales to specific factors like advertising, price changes, or external conditions such as weather – precisely the variance of these factors. In turn, this explains why MMMs are typically very greedy on data.</p>
<section id="why-variance-matters" class="level4">
<h4 class="anchored" data-anchor-id="why-variance-matters">Why Variance Matters</h4>
<p>Variance is essentially the “spread” or “dispersion” in data. When factors such as advertising spend, product pricing, and weather fluctuate, they create unique “patterns” in the data. These patterns allow MMM to distinguish the unique contribution of each factor to the overall sales. The model then estimates each variable’s impact by looking at how variations in these variables align with variations in sales over time.</p>
<p>To illustrate, imagine observing the temperature in a city where ice cream is sold. If the temperature were always a constant 25°C, there would be no variance in the temperature, and the model couldn’t estimate the effect of temperature on sales of the ice cream. However, if the temperature fluctuates the model can analyze how sales change as the temperature rises or falls, attributing a portion of the sales changes to temperature change.</p>
</section>
<section id="variance-and-independence" class="level4">
<h4 class="anchored" data-anchor-id="variance-and-independence">Variance and Independence</h4>
<p>Another crucial aspect of variance is how independent it is across variables. If variables such as advertising spend and temperature are strongly correlated – for example, if higher advertising spend always coincides with warmer weather – it becomes harder for the model to distinguish their effects. This issue, called&nbsp;<strong>multicollinearity</strong>, can obscure the true influence of each factor.</p>
<p>Ideally, each variable should have its own distinct and independent variance to enable the model to disentangle their contributions clearly. This is one reason why MMMs often require large, granular datasets – they help ensure sufficient variation and independence among factors.</p>
</section>
<section id="variance-as-the-key-to-disentangling" class="level4">
<h4 class="anchored" data-anchor-id="variance-as-the-key-to-disentangling">Variance as the Key to Disentangling</h4>
<p>In summary, variance is the foundation of how MMMs work. By identifying and analyzing differences in data, the model can separate the effects of multiple factors on sales. More variance means better opportunities to isolate these effects, making high-quality, diverse data essential for effective modeling. This ability to leverage variance is what gives MMMs their “magic” when it comes to attributing outcomes.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>This post does not strive for statistical correctness. It should rather provide an intuitional view on how it works.</p>
</div>
</div>
</div>
</section>
</section>
<section id="giving-intuition---ice-cream" class="level3">
<h3 class="anchored" data-anchor-id="giving-intuition---ice-cream">Giving Intuition - Ice Cream</h3>
<p>To demonstrate this in a simple example, let’s take an ice cream company and see how MMM might work to disentangle the effects of advertising, temperature, and price on sales.</p>
<section id="data-exploration" class="level4">
<h4 class="anchored" data-anchor-id="data-exploration">Data Exploration</h4>
<p>In this example, we’ll simulate weekly ice cream sales data over three years (152 weeks) along with three explanatory variables:</p>
<ul>
<li><p>advertising spend,</p></li>
<li><p>average weekly temperature,</p></li>
<li><p>and the price of ice cream.</p></li>
</ul>
<p>The ice creams sales (dependent variable) we want to explain by the three variables above (independent variables).</p>
<p>To not over-complicate things, in this example we assume the ice cream is sold in a market with warm temperatures (20°C - 35°C) across the year. Likewise we take the advertising spend into consideration, which is usually not best practice due to seasonality of media costs. That’s why one actually should use an activity metric. But in this example, for the sake of intuition, we remain with the spend. Furthermore the three independent variables are correlated to a a minimum.</p>
</section>
<section id="exploration-of-ice-cream-sales" class="level4">
<h4 class="anchored" data-anchor-id="exploration-of-ice-cream-sales">Exploration of Ice Cream Sales</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="1260"></p>
</figure>
</div>
</div>
</div>
<p>This is the time series of the sales of ice cream over 152 consecutive weeks. We can see lots of variation (weekly ups and downs of the sales). Typically, variation is captured using standardized metrics in statistics. Let’s explore this further.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_type</th>
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">numeric.mean</th>
<th style="text-align: right;">numeric.sd</th>
<th style="text-align: right;">numeric.p0</th>
<th style="text-align: right;">numeric.p25</th>
<th style="text-align: right;">numeric.p50</th>
<th style="text-align: right;">numeric.p75</th>
<th style="text-align: right;">numeric.p100</th>
<th style="text-align: left;">numeric.hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">sales</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">786.3433</td>
<td style="text-align: right;">142.7682</td>
<td style="text-align: right;">455.6699</td>
<td style="text-align: right;">687.173</td>
<td style="text-align: right;">786.4601</td>
<td style="text-align: right;">876.618</td>
<td style="text-align: right;">1186.034</td>
<td style="text-align: left;">▂▆▇▅▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The average weekly sales amount to 786 Euros, with a standard deviation of 142 Euros. This indicates that, on average, weekly sales fluctuate by approximately ±142 Euros around the mean. In other words, most weeks (about 68%, assuming a normal distribution) see sales between&nbsp;644 Euros and 928 Euros.</p>
<p>Further more we can see the min (percentile 0) and max (percentile 100), giving us the range of the variation, from 455 Euros to 1186 Euros.</p>
</section>
<section id="connection-with-sales" class="level4">
<h4 class="anchored" data-anchor-id="connection-with-sales">Connection with Sales</h4>
<p>No we need to go one step further and check the bi-variate connection of each factor impacting the sales. To visually inspect the connection properly, in statistics it is very common to use a scatter plot. Since ice cream sales is the dependent variable, we put this on the y-axis and the other variables on the x-axis.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Sales - Temperature</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Sales - Ad Spend</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Sales - Price</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="1260"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="1260"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="1260"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>We can clearly see: the warmer it is, the higher the sales. But also: the more is spent in advertising.<br>
And intuitively: the higher the price, the less the sales.</p>
</section>
<section id="creating-intuition" class="level4">
<h4 class="anchored" data-anchor-id="creating-intuition">Creating Intuition</h4>
<p>Now there is the problem going further: how can the model, which explains overall sales know, what is driven by what impacting factor and to what extend? As we already learned: it is about the variation. We will know give intuition about this concept and how it helps to disentangle the effects.</p>
<p>Therefore we will calculate the average of each indepentent variable and then for each week check if it is above average or below average. For each week and variable, the we calculate an indicator variables, showing if the actual value in the respective week is above or below the average. This information will be transformed into 1 and 0 accordingly. And then we paste the information in one string, and simply count the occurrence. The order of the string is: “temperature above everage”, “ad_spend_above_average” and “price_above_average”.</p>
<p>Lets see the result.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">combination</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0 0 0</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 0 1</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0 1 0</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 1 1</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 0 0</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 0 1</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 1 0</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 1 1</td>
<td style="text-align: right;">22</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>How to read this?</p>
<p>There is 22 cases in the data, where all the independent variables are above its average (1 1 1). And there is almost all possible combinations of being a variable above or below its average, e.g.&nbsp;16 occurences, where all thre independent variables are below average.</p>
<p>Now what we want to do this is, per group, add the average sales of this group.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">combination</th>
<th style="text-align: right;">average_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0 0 0</td>
<td style="text-align: right;">707.8060</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 0 1</td>
<td style="text-align: right;">619.2067</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0 1 0</td>
<td style="text-align: right;">824.0825</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 1 1</td>
<td style="text-align: right;">701.2840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 0 0</td>
<td style="text-align: right;">867.8043</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 0 1</td>
<td style="text-align: right;">818.0238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 1 0</td>
<td style="text-align: right;">937.6542</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 1 1</td>
<td style="text-align: right;">811.6645</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Thats very interesting. In the 16 weeks, where all variables are below its average, the average sales are 707,81 Euro. If the price increases above its average, the sales drops even more to 619,21 Euros (I would say, this forms the worst conditions for ice cream sales: colder temperatures, lower advertising and higher prices). Likewise, if it is warmer than the average, and the sales are supported by advertising and the prices are decreasing, then we see the hightest sales of 937,65 Euros.</p>
<p>Now lets make a twist, and arrange not by the combination but the average sales.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">combination</th>
<th style="text-align: right;">average_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0 0 1</td>
<td style="text-align: right;">619.2067</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 1 1</td>
<td style="text-align: right;">701.2840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0 0 0</td>
<td style="text-align: right;">707.8060</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 1 1</td>
<td style="text-align: right;">811.6645</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 0 1</td>
<td style="text-align: right;">818.0238</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 1 0</td>
<td style="text-align: right;">824.0825</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 0 0</td>
<td style="text-align: right;">867.8043</td>
</tr>
<tr class="even">
<td style="text-align: left;">1 1 0</td>
<td style="text-align: right;">937.6542</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can see that we see the “1” at the start of the combination, indicating the weather, is rather at the bottom. Hence we can generalize: the warmer, the more ice cream sold. We can on the opposite see, the negative impact of the price. For the ad spend it is not so clear. What we can conclude here is, that the model will most likley come to the conclusion, that the price as such as a negative impact (negativ sign). And also that temperature will most likely have the strongest positive impact on sales.</p>
</section>
<section id="actual-model" class="level4">
<h4 class="anchored" data-anchor-id="actual-model">Actual Model</h4>
<p>Lets check the assumption from the previous chapter and create the model.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Not Standardized</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Standardized</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ (temperature) + (ad_spend) + (price), data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-319.80  -62.19   -1.21   59.89  236.74 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.984e+02  6.653e+01   7.491 5.73e-12 ***
temperature  1.907e+01  1.793e+00  10.635  &lt; 2e-16 ***
ad_spend     3.615e-02  7.156e-03   5.053 1.27e-06 ***
price       -1.457e+02  1.766e+01  -8.249 8.02e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 95.06 on 148 degrees of freedom
Multiple R-squared:  0.5654,    Adjusted R-squared:  0.5566 
F-statistic: 64.19 on 3 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ scale(temperature) + scale(ad_spend) + scale(price), 
    data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-319.80  -62.19   -1.21   59.89  236.74 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         786.343      7.711 101.982  &lt; 2e-16 ***
scale(temperature)   82.400      7.748  10.635  &lt; 2e-16 ***
scale(ad_spend)      39.222      7.763   5.053 1.27e-06 ***
scale(price)        -63.979      7.756  -8.249 8.02e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 95.06 on 148 degrees of freedom
Multiple R-squared:  0.5654,    Adjusted R-squared:  0.5566 
F-statistic: 64.19 on 3 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The best way to compare the coefficients is the standardized view, as each independent variable has a different scale (e.g., euros, degrees Celsius). Standardization brings all variables onto the same scale by centering them around their mean and dividing by their standard deviation. This ensures that the effects are comparable, regardless of their original units. A higher standardized coefficient indicates which factor has the strongest influence, independent of its initial scale.</p>
<p>The model results confirm our assumptions.&nbsp;<strong>Temperature</strong>&nbsp;has the strongest positive impact on sales, with a standardized coefficient of&nbsp;<strong>82.4</strong>, followed by&nbsp;<strong>advertising spend</strong>&nbsp;at&nbsp;<strong>39.2</strong>.&nbsp;<strong>Price</strong>, as expected, has a negative impact, with a coefficient of&nbsp;<strong>-63.98</strong>, meaning higher prices significantly reduce sales. All these coefficients are statistically significant at the&nbsp;<strong>p &lt; 0.001</strong>level, showing robust relationships.</p>
<p>The model explains approximately&nbsp;<strong>56.5% of the variation</strong>&nbsp;in sales (<strong>R-squared = 0.5654</strong>) and has a residual standard error of&nbsp;<strong>95.06</strong>. The explanation of variance is not the best, and I would be rather careful with this model. Obviously there is sales-driving factors, which are not captured in the model (e.g.&nbsp;could be the friendliness of the sales staff, the selling place, but also the economic situation of the clients).</p>
<p>In summary, warmer temperatures and increased advertising positively influence sales, while higher prices reduce them, with temperature being the dominant driver.</p>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This post aimed to provide an intuitive understanding of how Marketing Mix Models disentangle effects. By leveraging variance and observing patterns in data, MMM can quantify the impact of different factors like temperature, advertising, and price on sales. Standardizing variables ensures fair comparisons of their influence, while analyzing combinations of factors reveals deeper insights into their interactions.</p>
<p>In practice, MMMs are invaluable tools for understanding what drives sales, but their accuracy depends on data quality and variance. By applying these principles, businesses can make more informed marketing decisions.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/funalytics\.de");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Christian Jaehnert</p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
<p>This website is built with ❤️ and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>